golang-queue/queue

- README.md
- queue_test.go
> chore: testing queue is full.

- .drone.yml
- .github/workflows/go.yml
- go.mod
- go.sum
- nsq/README.md
- nsq/nsq.go
- nsq/nsq_test.go
> chore: support NSQ worker.

- nsq/nsq.go
- nsq/nsq_test.go
- simple/simple.go
> chore(nsq): pass the QueuedMessage interface as parameter

- nsq/nsq.go
- nsq/nsq_test.go
> chore: Add testing default flow

- README.md
- _example/simple/go.mod
- _example/simple/go.sum
- _example/simple/main.go
> docs: add simple example

- logger.go
- logger_test.go
- queue.go
- queue_test.go
- simple/simple.go
- simple/simple_test.go
partial implementation for a simple queue. #16 
> chore(queue): support job timeout setting.

- simple/simple.go
> chore(simple): support stop flag

- README.md
- _example/simple/go.mod
- _example/simple/go.sum
- _example/simple/main.go
> chore(simple): update simple queue example

- queue.go
- queue_test.go
> chore: close queue after shutdown.

- queue.go
- simple/simple.go
> chore: Add job timeout in body with bytes format.

- queue.go
> chore: fix timeout bugs

- nsq/nsq.go
- nsq/nsq_test.go
ref https://github.com/appleboy/queue/issues/16
> chore(NSQ): support job timeout

- nats/nats.go
- nats/nats_test.go
> chore(NATS): support job timeout.

- queue.go
- queue_test.go
- simple/simple.go
- simple/simple_test.go
- worker.go
> chore(queue): Support task function

- .github/workflows/go.yml
- consumer.go
- consumer_test.go
> chore: move simple package to top

- .github/workflows/go.yml
> chore(CI): add go1.7 and cache library

- consumer.go
- consumer_test.go
- options.go
- queue.go
> chore: Add options

- pool.go
- pool_test.go
- queue.go
> chore: Support new pool

- _example/example01/go.mod
- _example/example01/go.sum
- _example/example01/main.go
- _example/example02/go.mod
- _example/example02/go.sum
- _example/example02/main.go
> chore: update example

- consumer.go
- consumer_test.go
- queue_test.go
- worker.go
- worker_empty.go
- worker_message.go
- worker_task.go
> chore(metric): support busy workers count.

- .github/workflows/go.yml
> chore(lint): upgrade golangci-lint to v1.43.0

- options.go
chore: add customized timeout setting function
> need to customized timeout in struct Options

- consumer_test.go
- queue.go
fix https://github.com/golang-queue/queue/issues/49
> feat(worker): update node count dynamically

- consumer.go
- consumer_test.go
- errors.go
- queue.go
fix https://github.com/golang-queue/queue/issues/55
> feat(queue): all task has been done after closing the channel

- consumer.go
fix: https://github.com/golang-queue/queue/issues/57
> feat(consumer): add default timeout in Request new task

- consumer.go
- consumer_test.go
fix https://github.com/golang-queue/queue/issues/67
> chore(consumer): handle all job before shutdown.

- logger.go
- Add imports for `path/filepath` and `runtime`
- Remove `log.Lshortfile` from logger initialization
- Add `logWithCallerf` method to include caller information in formatted log messages
- Add `logWithCaller` method to include caller information in log messages
- Update `Errorf` method to use `logWithCallerf` for logging
- Update `Fatalf` method to use `logWithCallerf` for logging and ensure program exit
- Update `Error` method to use `logWithCaller` for logging
- Update `Fatal` method to use `logWithCaller` for logging and ensure program exit
> refactor: enhance logging with caller information and structured output
