golang-queue/queue

- nsq/nsq.go
- nsq/nsq_test.go
- queue.go
- simple/simple.go
- simple/simple_test.go
- worker.go
fixed https://github.com/appleboy/queue/issues/11
> chore: add stop channel in worker

- queue.go
- simple/simple.go
- simple/simple_test.go
1. Add `stopFlag` in Queue
2. handle the job process if receive the stop signal
> chore: Add stop flag in Queue and refactor to handle stop flow

- consumer.go
- metric.go
- options.go
> chore(metric): Add metric interface

- .golangci.yml
- consumer.go
- consumer_test.go
- pool_test.go
- queue.go
- queue_test.go
- worker.go
- worker_empty.go
- worker_message.go
- worker_task.go
fix https://github.com/golang-queue/queue/issues/43
> chore(queue): auto scale the task worker

- consumer.go
- queue.go
- worker.go
- worker_empty.go
- worker_message.go
- worker_task.go
fix: https://github.com/golang-queue/queue/issues/45
> chore(worker): remove BeforeRun and AfterRun interface

- metric.go
- metric_test.go
- queue.go
- queue_test.go
- worker.go
- worker_empty.go
- worker_message.go
- worker_task.go
```go
type metric struct {
busyWorkers    uint64
successTasks   uint64
failureTasks   uint64
submittedTasks uint64
}
```
fix https://github.com/golang-queue/queue/issues/47
> feat(metric): add success, failure and submitted tasks

- consumer.go
- consumer_test.go
- queue.go
fix https://github.com/golang-queue/queue/issues/53
> fix(worker): handle all jobs with graceful shutdown

- pool_test.go
- queue.go
check worker count is zero or not before fetch the task.
fix https://github.com/golang-queue/queue/issues/59
> fix(worker): don't start request task

- queue.go
- queue_test.go
- worker_test.go
> chore(queue): don't prepare request data before worker done.

- queue_example_test.go
> chore(queue): add example testing.

- queue.go
> fix(error): missing panic error message

- .github/workflows/go.yml
- consumer.go
- consumer_test.go
- go.mod
- go.sum
- queue.go
- queue_test.go
- worker_task.go
[49894bf](https://github.com/golang-queue/queue/pull/72/commits/49894bf9a85a767e0564f8f8cc1ce75bb2bf60f0)
```sh
goos: linux
goarch: amd64
pkg: github.com/golang-queue/queue
cpu: Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
BenchmarkQueueTask
INFO: 2022/05/29 04:18:27 logger.go:35: shutdown all tasks: 5 workers
BenchmarkQueueTask-2   	     584	   2079968 ns/op	    1801 B/op	      30 allocs/op
BenchmarkQueue
INFO: 2022/05/29 04:18:28 logger.go:35: shutdown all tasks: 5 workers
INFO: 2022/05/29 04:18:28 logger.go:35: shutdown all tasks: 5 workers
INFO: 2022/05/29 04:18:29 logger.go:35: shutdown all tasks: 5 workers
BenchmarkQueue-2       	 1892185	       624.9 ns/op	     214 B/op	       5 allocs/op
PASS
ok  	github.com/golang-queue/queue	2.924s
``` …
> test(benchmark): add queue performance check

- consumer.go
- consumer_test.go
- job/job.go
- job/option.go
fix #84 
Signed-off-by: Bo-Yi.Wu <appleboy.tw@gmail.com>
> chore(job): support retry count and delay between retry

- consumer.go
- consumer_test.go
- options.go
fix https://github.com/golang-queue/queue/issues/89
Signed-off-by: Bo-Yi.Wu <appleboy.tw@gmail.com>
> chore(consumer): support request timeout flag

- benchmark_test.go
- consumer.go
```
goos: linux
goarch: amd64
pkg: github.com/golang-queue/queue
cpu: Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
BenchmarkNewCusumer
BenchmarkNewCusumer-2        	15561048	        81.93 ns/op	       0 B/op	       0 allocs/op
BenchmarkNewCusumer-2        	15640579	        77.76 ns/op	       0 B/op	       0 allocs/op
BenchmarkNewCusumer-2        	15296659	        78.49 ns/op	       0 B/op	       0 allocs/op
BenchmarkNewCusumer-2        	15797636	        77.23 ns/op	       0 B/op	       0 allocs/op
BenchmarkNewCusumer-2        	15114574	        80.24 ns/op	       0 B/op	       0 allocs/op
BenchmarkQueueTask
BenchmarkQueueTask-2         	13314780	        89.42 ns/op	      70 B/op	       1 allocs/op
BenchmarkQueueTask-2         	13111341	        89.77 ns/op	      70 B/op	       1 allocs/op …
```
> chore(queue): replace channel queue with ring buffer queue.

- consumer.go
- options.go
Signed-off-by: Bo-Yi.Wu <appleboy.tw@gmail.com>
> chore(options): update default capacity as zero

- job/job.go
- queue.go
```sh
Run go test -v -run=^$ -count 5 -benchmem -bench . ./...
goos: darwin
goarch: amd64
pkg: github.com/golang-queue/queue
cpu: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
BenchmarkQueue
BenchmarkQueue-3         	 2442654	       498.4 ns/op	     270 B/op	       4 allocs/op
BenchmarkQueue-3         	 2472348	       504.0 ns/op	     270 B/op	       4 allocs/op
BenchmarkQueue-3         	 2351935	       514.6 ns/op	     273 B/op	       4 allocs/op
BenchmarkQueue-3         	 2384654	       517.1 ns/op	     272 B/op	       4 allocs/op
BenchmarkQueue-3         	 2268847	       527.1 ns/op	     275 B/op	       4 allocs/op
```
```sh
54s
Run go test -v -run=^$ -count 5 -benchmem -bench . ./...
goos: darwin
goarch: amd64
pkg: github.com/golang-queue/queue
cpu: Intel(R) Xeon(R) CPU E5-1650 v2 @ …
```
> chore(queue): don't allocate new message

- benchmark_test.go
- core/worker.go
- go.mod
- go.sum
- job/job.go
- job/job_test.go
- queue.go
See the reference: [Serialize a struct to bytes to send it through the network in Go — Part I](https://medium.com/@maximgradan/serialize-a-struct-to-bytes-to-send-it-through-the-network-in-go-part-i-b861c15d2f06)
```sh
BenchmarkEncode
BenchmarkEncode/JSON
BenchmarkEncode/JSON-2                               	 6139400	       189.3 ns/op	      96 B/op	       1 allocs/op
BenchmarkEncode/JSON-2                               	 6316482	       189.1 ns/op	      96 B/op	       1 allocs/op
BenchmarkEncode/JSON-2                               	 6304340	       189.5 ns/op	      96 B/op	       1 allocs/op
BenchmarkEncode/JSON-2                               	 6285771	       189.5 ns/op	      96 B/op	       1 allocs/op
BenchmarkEncode/JSON-2                               	 6304476	       188.7 ns/op …
```
> chore(job): serialize a struct to bytes

- .github/workflows/go.yml
- queue.go
- ring.go
- ring_test.go
- Enable race condition detection in Go tests by adding `-race` flag
- Refactor `Queue` to use a local variable for `workerCount` with proper locking
- Refactor `Ring` to use a local variable for `count` with proper locking and defer unlocking
- Replace direct access to `busyWorkers` metric with `BusyWorkers()` method in tests
> refactor(goroutine): improve concurrency safety and testing

- options.go
- queue.go
From my debugging it seems the `Wait` API will never return until `Shutdown` is called.
I needed a way to reliably know when all jobs were done being called.
This adds a new queue option to call a function after a job is done and the metric counters have been updated in the defer of `work`.
Very simple but allows for an event based tracking on the queue.
If there its a better way, would love to know but this is the solution I am using for now.
Kudos.
@appleboy
> feat: add ability to call a function after the job function runs

- metric.go
- metric_test.go
- options.go
- pool.go
- pool_test.go
- queue.go
- queue_test.go
- ring_test.go
- Change `BusyWorkers` type from `uint64` to `int64`
- Add `CompletedTasks` method to `Metric` interface and implementation
- Update `IncBusyWorker` and `DecBusyWorker` to use `atomic.AddInt64`
- Modify test assertions to use `uint64` and `int64` types
- Change `defaultWorkerCount` and related functions from `int` to `int64`
- Update `NewPool` and related functions to use `int64` for size and worker count
- Add `CompletedTasks` method to `Queue` and update related methods to use `uint64` and `int64` types
> refactor: refactor worker and task metrics to use int64 types

- benchmark_test.go
- core/worker.go
- job/job.go
- job/job_test.go
- queue.go
- queue_test.go
- ring.go
- Remove `Encode` method call in `BenchmarkQueue` function
- Add `TaskMessage` interface extending `QueuedMessage` with `Payload` method
- Rename `Payload` field to `Body` in `Message` struct
- Add `Payload` method to `Message` struct to return `Body`
- Replace `Data` field and `Encode` method in `Message` struct with `Bytes` method using JSON marshalling
- Update `NewMessage` to use `Body` instead of `Payload`
- Add documentation for `Encode` method in `job` package
- Update `TestMessageEncodeDecode` to use `Payload()` method
- Replace `Encode` method call with direct handling of `task` in `Queue` methods
- Change logger from `Errorf` to `Fatalf` in `Queue` error handling
- Add type assertion and handling for `job.Message` in `Queue`'s `run` method
- Import `job` package in `ring.go`
- …
> refactor: refactor message handling and encoding in queue system

- metric.go
- queue.go
- Remove `IncCompletedTask` method from `Metric` interface
- Remove `completedTasks` field from `metric` struct
- Remove `IncCompletedTask` method implementation
- Update `CompletedTasks` method to return the sum of `successTasks` and `failureTasks`
- Remove call to `IncCompletedTask` in `Queue`'s `work` method
> refactor: refactor metric handling by removing IncCompletedTask method

- options.go
- options_test.go
- queue.go
- Import `time` package
- Add `WithRetryInterval` function to set retry intervals
- Add `retryInterval` field to `Options` struct with default value of 1 second
- New file `options_test.go` for testing `WithRetryInterval` functionality with various durations
- Add `retryInterval` field to `Queue` struct
- Initialize ticker with `retryInterval` in `Queue` and update its usage in `start` method
ref: https://github.com/golang-queue/queue/issues/142
> feat: add configurable retry interval for queue retries

- queue.go
- Add `notify` channel to `Queue`
- Notify worker in the `queue` function without blocking the main thread
- Add case to listen for `notify` channel in the `start` function
fixed #144 #142
> feat: implement listener for asynchronous notifications in queue
